[package]
name = "goshenite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# winit is a cross-platform window creation and management library
winit = "0.26.1"
# glam is a vector and math library well suited for 3D graphics
glam = "0.20.5"
# ash is a lightweight vulkan wrapper
ash = { version = "0.37.0", default-features = false, features = ["linked", "debug"] }
ash-window = "0.10.0"

# egui
# slotmap
# ECS: specs

[build-dependencies]
shaderc = "0.8.0"
