[package]
name = "goshenite"
version = "0.1.0"
edition = "2021"

[features]
x11 = ["winit/x11"]
wayland = ["winit/wayland", "winit/wayland-dlopen"]

[dependencies]
# winit is a cross-platform window creation and management library
winit = { version = "0.26", default-features = false }
# glam is a vector and math library well suited for 3D graphics
glam = "0.20"
# ash is a lightweight vulkan wrapper
ash = { version = "0.37", default-features = false, features = ["linked", "debug"] }
ash-window = "0.10"
# terminal output
colored = "2.0"

# egui
# slotmap
# specs: ECS
# rayon: parallelize iterators etc

[build-dependencies]
shaderc = "0.8"
