[package]
name = "goshenite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9"
log = "0.4"
glam = "0.20" # note SIMD requres flags for x86 and wasm32 (on by default on x86_64)
wgpu = "0.12"
winit = "0.26"
pollster = "0.2"
bytemuck = { version = "1.7", features = [ "derive" ] }

# egui = "0.15"
# slotmap = "1.0"
# ECS: specs = "0.17"
